# frozen_string_literal: true
source 'https://rubygems.org'

# Specify your gem's dependencies in valkyrie.gemspec
gemspec

# Necessary for the --ignore-parent-exclusion feature. Remove when
# https://github.com/bbatsov/rubocop/pull/4329 is merged.
gem 'rubocop', github: 'nelsonjr/rubocop', ref: 'a5db18a49b9f318644ae7209c73452fb7bbcdc49'
