# frozen_string_literal: true
source 'https://rubygems.org'

# Specify your gem's dependencies in valkyrie.gemspec
gemspec
gem 'rubocop', github: 'nelsonjr/rubocop', ref: 'a5db18a49b9f318644ae7209c73452fb7bbcdc49'
